name: 'Run Cypress Tests Vs API Service'
description: 'Runs Terminus API Service Cypress Tests'
inputs:
  environment:
    description: 'The environment against which to run tests (ex: ninja)'
    required: true
  repo:
    description: 'The repo name containing the service being tested and its tests.'
    required: true
  repo_owner:
    description: 'The owner of the service/test repo'
    required: false
    default: 'GetTerminus'
  repo_ref:
    description: 'The ref to get for the service/test repo'
    required: false
    default: 'main'
  repo_checkout_token:
    description: 'The GH token that can pull down the service/test repo.'
    required: true
  repo_cypress_dir:
    description: 'The directory within the service/test repo containing the Cypress tests'
    required: false
    default: 'cypress-e2e'
  cypress_browser:
    description: 'The browsers to test against'
    required: false
    default: 'chrome'
  # example environment_vars:
  # At MINIMUM CYPRESS_RECORD_KEY is required
  # '[{"var":"CYPRESS_RECORD_KEY=''xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx''"},{"var":"CYPRESS_ts_user_email=''email@something.com''"}]'
  environment_vars:
    description: 'Stringified JSON array payload of environment variables to set'
    required: true
  test_tags:
    description: 'Cypress tags to run'
    required: false
    default: '@SMOKE'

runs:
  using: "composite"
  steps:
    - name: Checkout Service
      uses: actions/checkout@v2
      with:
        repository: "${{ inputs.repo_owner }}/${{ inputs.repo }}"
        ref: ${{ inputs.repo_ref }}
        token: ${{ inputs.repo_checkout_token }}

    - name: Yarn Install
      uses: shell
      run: |
        cd ${{ inputs.repo_cypress_dir }}
        yarn install

    - name: Parse Env vars
      uses: sergeysova/jq-action@v2
      id: environment_vars
      with:
        cmd: 'jq ''.[] | .var'' ${{ environment_vars }} -r'
        multline: true
    
    - name: Set Env vars
      uses: shell
      run: |
        environment_vars="${{ steps.environment_vars.outputs.value }}"
        for environment_var in $environment_vars; do
          export "$environment_var"
        done

    - name: Run Tests
      uses: cypress-io/github-action@v2
      with:
        config: video=true
        command-prefix: yarn
        browser: ${{ github.event.inputs.cypress_browser }}
        headless: true
        tag: 'API-${{ github.event.inputs.cypress_browser }},${{ github.event.inputs.environment }}'
        record: true
        parallel: true
        working-directory: ${{ github.events.inputs.repo_cypress_dir }}
        ci-build-id: ${{ needs.prepare.outputs.uuid }}
      env:
        YARN_NODE_LINKER: pnp
        CYPRESS_grepTags: ${{ github.event.inputs.test_tags }}
        DD_ENV: ${{ github.event.inputs.environment }}
        DD_SERVICE: ${{ inputs.repo }}
