name: 'Terraform Deploy - Multiple Workspaces'
description: 'Triggers a deployment of all environments.'
inputs:
  gh_deployment_access_token:
    description: '[secret] GitHub deployment access token.'
    required: true
  environment:
    description: 'target deployment environment'
    default: all
    required: false
runs:
  using: "composite"
  steps:
  - name: Create Sequential Deployments
    uses: chrnorm/deployment-action@releases/v1
    with:
      token: ${{ inputs.gh_deployment_access_token }}
      environment: ${{ inputs.environment }}
      use_delivery_bot: true
      
