name: 'Terraform Deploy - Multiple Workspaces'
description: 'Triggers a deployment of all environments.'
inputs:
  gh_deployment_access_token:
    description: '[secret] GitHub deployment access token.'
    required: true
  environment:
    description: 'target deployment environment'
    default: all
    required: false
runs:
  using: "composite"
  steps:
    - name: Set SCRIPT_SOURCE
      run: |
        cd /home/runner/work/_actions/GetTerminus/terminus-github-actions/*/shell-scripts
        dir=$(pwd)
        echo "SCRIPT_SOURCE=$dir" >> $GITHUB_ENV
      shell: bash
    - name: Validate Inputs
      working-directory: ${{ env.SCRIPT_SOURCE }}
      env:
        GH_DEPLOYMENT_ACCESS_TOKEN: ${{ inputs.gh_deployment_access_token }}
      run: |
        source input-validator.sh

        declare -A inputs
        inputs[gh_deployment_access_token]="$GH_DEPLOYMENT_ACCESS_TOKEN"

        validateInput inputs
      shell: bash
    - name: Create Sequential Deployments
      uses: chrnorm/deployment-action@releases/v1
      with:
        token: ${{ inputs.gh_deployment_access_token }}
        environment: ${{ inputs.environment }}
        use_delivery_bot: true
