name: 'Terraform Deploy - Multiple Workspaces'
description: 'Triggers a deployment of all environments.'
inputs:
  gh_deployment_access_token:
    description: '[secret] GitHub deployment access token.'
    required: true
runs:
  using: "composite"
  steps:
  - name: Create Sequential Deployments
    uses: chrnorm/deployment-action@releases/v1
    with:
      token: ${{ inputs.gh_deployment_access_token }}
      environment: all