name: 'Terraform State Unlock'
description: 'Unlocks the terraform state file using the lock id.'
inputs:
  ssh_key:
    description: '[secret] [required] GitHub SSH Key for pulling repo.'
    required: true
  terraform_version:
    description: '[decimal] [required] (i.e. 1.0.11) Terraform version to use.'
    required: true
  lock_id:
    description: "[lock_id] (e.g. 8b08ccb1-f514-e9c5-7271-88f5c13c3155) ID of the TF lock to unlock."
    required: true

runs:
  using: "composite"
  steps:
    - name: Validate Inputs
      env:
        SSH_KEY: ${{ inputs.ssh_key }}
        TERRAFORM_VERSION: ${{ inputs.terraform_version }}
        LOCK_ID: ${{ inputs.lock_id }}
      run: |
        cd ${{ github.action_path }}
        source ../../shell-scripts/input-validator.sh
        
        declare -A inputs
        inputs[ssh_key]="$SSH_KEY"
        inputs[terraform_version]="$TERRAFORM_VERSION"
        inputs[lock_id]="$LOCK_ID"
        
        validateInput inputs
      shell: bash
    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ inputs.ssh_key }}
    - name: Pull
      uses: actions/checkout@v2
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        terraform_version: ${{ inputs.terraform_version }}
    - name: Unlock Terraform State File
      run: |
        terraform version
        terraform init -lock=false -input=false
        terraform force-unlock -force ${{ inputs.lock_id }}
      shell: bash
        
