name: 'Terraform Plan - Multiple Workspaces'
description: 'Runs a terraform plan for a for a repo with a multiple workspaces (i.e. most terminus repos).'
inputs:
  ssh_key:
    description: '[secret] GitHub SSH Key for pulling repo.'
    required: true
  terraform_version:
    description: '[decimal] (i.e. 1.0.11) Terraform version to use.'
    required: true
  tf_workspace:
    description: '[string] (i.e. ninja/prod-east) TF Workspace to create if tf_create_workspace input = true.'
    required: true
  github_token:
    description: '[secret] Github token for plan commenter to use.'
    required: true
  artifactory_enabled:
    description: '[bool] (i.e. true/false) Whether or not the repo uses artifactory for the helm chart.'
    default: 'false'
    required: false
  artifactory_read_access_token:
    description: '[secret] Read access token for artifactory.'
    required: false
  artifactory_helm_chart_path:
    description: '[string] Path to helm chart for artifactory.'
    required: false
  enable_plan_commenter:
    description: '[bool] (i.e. true/false) Enable the tf plan commenter.'
    required: false
    default: 'true'
  tf_create_workspace:
    description: '[bool] (i.e. true/false) If set to true, workspace will be
                  created based on tf_workspace input variable. This should only be run when
                  creating the repo and running the plan for the first time and
                  removed after.'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Validate Inputs
      env:
        SSH_KEY: ${{ inputs.ssh_key }}
        TERRAFORM_VERSION: ${{ inputs.terraform_version }}
        TF_WORKSPACE: ${{ inputs.tf_workspace }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        cd ${{ github.action_path }}
        source ../../shell-scripts/input-validator.sh

        declare -A inputs
        inputs[ssh_key]="$SSH_KEY"
        inputs[terraform_version]="$TERRAFORM_VERSION"
        inputs[tf_workspace]="$TF_WORKSPACE"
        inputs[github_token]="$GITHUB_TOKEN"

        validateInput inputs
      shell: bash
    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ inputs.ssh_key }}
    - name: Pull
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Helm Update
      if: ${{ inputs.artifactory_enabled == 'true' }}
      run: |
        helm repo add terminus https://getterminus.jfrog.io/artifactory/default-helm/ --username developer --password ${{ inputs.artifactory_read_access_token }}
        helm repo update
        helm dependency update ${{ inputs.artifactory_helm_chart_path }}
      shell: bash
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        terraform_version: ${{ inputs.terraform_version }}
    - name: Terraform Format Check
      id: fmt
      run: |
        terraform fmt -check -recursive || echo "::set-output name=exitcode_continue_on_error::$?"
      #TODO: Uncomment once github supports it
      #continue-on-error: true
      shell: bash
    - name: Post TF Format Check
      if: ${{ always() && github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}
      uses: GetTerminus/terraform-pr-commenter@master
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        EXPAND_SUMMARY_DETAILS: "false"
      with:
        commenter_type: fmt
        commenter_input: ${{ format('{0}{1}', steps.fmt.outputs.stdout, steps.fmt.outputs.stderr) }}
        commenter_exitcode: ${{ steps.fmt.outputs.exitcode }}
        terraform_version: ${{ inputs.terraform_version }}
    - name: TF Plan - Initialize
      id: init
      run: |
        terraform version
        terraform init -lock=false -input=false
      shell: bash
    - name: Post TF Init Comment
      # TODO: Add in the below code to all plan commenter if statements when github adds in the functionality
      # (steps.init.outcome == 'success' || steps.init.outcome == 'failure')
      if: ${{ always() && github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}
      uses: GetTerminus/terraform-pr-commenter@master
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        EXPAND_SUMMARY_DETAILS: "false"
      with:
        commenter_type: init
        commenter_input: ${{ format('{0}{1}', steps.init.outputs.stdout, steps.init.outputs.stderr) }}
        commenter_exitcode: ${{ steps.init.outputs.exitcode }}
        terraform_version: ${{ inputs.terraform_version }}
    - name: TF Plan - Select Workspace
      if: ${{ inputs.tf_create_workspace != 'true' }}
      run: |
        terraform workspace select ${{ inputs.tf_workspace }}
      shell: bash
    - name: TF Plan - Create Workspace
      if: ${{ inputs.tf_create_workspace == 'true' }}
      run: |
        terraform workspace new ${{ inputs.tf_workspace }}
        terraform workspace select ${{ inputs.tf_workspace }}
      shell: bash
    - name: TF Plan - Validate
      id: validate
      run: |
        terraform validate
        terraform workspace show
      shell: bash
    - name: Post TF Validate Comment
      if: ${{ always() && github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}
      uses: GetTerminus/terraform-pr-commenter@master
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        EXPAND_SUMMARY_DETAILS: "false"
      with:
        commenter_type: validate
        commenter_input: ${{ format('{0}{1}', steps.validate.outputs.stdout, steps.validate.outputs.stderr) }}
        commenter_exitcode: ${{ steps.validate.outputs.exitcode }}
        terraform_version: ${{ inputs.terraform_version }}
    - name: TF Plan - Run
      id: plan
      run: |
        terraform plan -var-file=vars/${{ inputs.tf_workspace }}.tfvars -lock=false -input=false -out=tfplan
      shell: bash
    - name: Post TF Plan Comment
      if: ${{ always() && github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && inputs.enable_plan_commenter == 'true' }}
      uses: GetTerminus/terraform-pr-commenter@master
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        EXPAND_SUMMARY_DETAILS: "false"
        TF_WORKSPACE: ${{ inputs.tf_workspace }}
      with:
        commenter_type: plan
        commenter_input: tfplan
        commenter_exitcode: ${{ steps.plan.outputs.exitcode }}
        terraform_version: ${{ inputs.terraform_version }}
    - name: Get Local Service Name
      id: service_name
      run: |
        echo "::set-output name=service_name::$(terraform output service_name || echo "false")" || echo "::set-output name=exitcode_continue_on_error::$?"
      shell: bash
#    - name: Run Datadog Synthetics tests
#      if: ${{ steps.service_name.outputs.service_name }}
#      uses: DataDog/synthetics-ci-github-action@v0.2.2
#      with:
#        api_key: $DATADOG_API_KEY
#        app_key: $DATADOG_APP_KEY
#        test_search_query: 'tag:${{ steps.service_name.outputs.service_name }}'
    - name: Warn if service_name Output is not Set
      if: ${{ !steps.service_name.outputs.service_name }}
      run: |
        echo "::warning title=service_name not set::service_name is not set as a terraform output."
        printf "\nIn order to automatically trigger datadog synthetic tests\nand to prevent errors being deployed to prod,\nplease set service_name as an output in locals.tf like below\n"
        printf "output service_name {\n"
        printf "  value = local.service_name\n"
        printf "}"
      shell: bash
