name: 'Spark Build'
description: 'Runs a Spark build.'
inputs:
  ssh_key:
    description: '[secret] GitHub SSH Key for pulling repo.'
    required: true
  spark_lib_image:
    description: '[string] source of the spark lib package docker image.'
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ inputs.ssh_key }}
    - name: Pull
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: package_spark_lib
      uses: ${{ inputs.spark_lib_image }}
      with:
        args: bash -c "cd spark-lib && sbt test"
        
