name: 'Terraform Deploy EKS - Single Workspace'
description: 'Triggers a workflow dispatch of EKS Infra - Terraform Apply.'
inputs:
  pull_access_token:
    description: '[secret] Github pull access token.'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set SCRIPT_SOURCE
      run: |
        cd /home/runner/work/_actions/GetTerminus/terminus-github-actions/*/shell-scripts
        dir=$(pwd)
        echo "SCRIPT_SOURCE=$dir" >> $GITHUB_ENV
      shell: bash
    - name: Validate Inputs
      working-directory: ${{ env.SCRIPT_SOURCE }}
      env:
        PULL_ACCESS_TOKEN: ${{ inputs.pull_access_token }}
      run: |
        source input-validator.sh

        declare -A inputs
        inputs[pull_access_token]="$PULL_ACCESS_TOKEN"

        validateInput inputs
      shell: bash
    - name: Deploy EKS Infra
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Terraform Apply
        token: ${{ inputs.pull_access_token }}
        repo: GetTerminus/eks-infra
        ref: master
        inputs: '{"environment": "all", "use_delivery_bot": "false"}'
