name: 'Terraform Deploy EKS - Single Workspace'
description: 'Triggers a workflow dispatch of EKS Infra - Terraform Apply.'
inputs:
  gh_deployment_access_token:
    description: '[secret] GitHub deployment access token.'
    required: true
  environment:
    description: 'target deployment environment'
    default: all
    required: false
runs:
  using: "composite"
  steps:
    - name: Validate Inputs
      env:
        PULL_ACCESS_TOKEN: ${{ inputs.pull_access_token }}
      run: |
        cd ${{ github.action_path }}
        source ../../shell-scripts/input-validator.sh

        declare -A inputs
        inputs[pull_access_token]="$PULL_ACCESS_TOKEN"

        validateInput inputs
      shell: bash
    - name: Create Sequential Deployments
      uses: chrnorm/deployment-action@releases/v2
      with:
        token: ${{ inputs.gh_deployment_access_token }}
        environment: ${{ inputs.environment }}
        repo: eks-infra
