name: Release Beta

on:
  push:
    branches-ignore:
      - main

jobs:
  release-beta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sersoft-gmbh/running-release-tags-action@v1
        with:
          tag: v1-beta
          create-release: false
          github-token: ${{secrets.GITHUB_TOKEN}}
