name: Release Beta

on:
  push:
    branches-ignore:
      - main

jobs:
  release-beta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Beta Git tag
        uses: weareyipyip/walking-tag-action@v1
        with:
          tag-name: v1-beta
          tag-message: The current beta is based on this commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
