name: Release

on:
  push:
    branches: [ dpr-add-auto-tagger ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump and Push Tag Version
        uses: hennejg/github-tag-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: dpr-add-auto-tagger
          create_annotated_tag: true
      - uses: kellyselden/move-semver-tags-action@v3
        with:
          copy-annotations: true
