name: Release Beta

on:
  push:
    branches-ignore:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_release_rules: "*:patch"
          pre_release_branches: "${{ github.ref_name }}"
          append_to_pre_release_tag: "-beta"
          dry_run: true
#      - uses: sersoft-gmbh/running-release-tags-action@v1
#        with:
#          tag: ${{ steps.tag_version.outputs.new_tag }}
#          suffix-regex:
#          github-token: ${{secrets.GITHUB_TOKEN}}
